CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  first_name    VARCHAR2(50),
  last_name     VARCHAR2(50),
  phone_number  VARCHAR2(15),
  email         VARCHAR2(30) UNIQUE,
  password      VARCHAR2(45),
  date_of_birth DATE,
  is_active     NUMBER(1) DEFAULT 1,
  CONSTRAINT pk_users PRIMARY KEY(id)
);

CREATE TABLE reservations (
  id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  user_id             NUMBER,
  date_of_reservation DATE   DEFAULT SYSDATE,
  amount_of_children  NUMBER DEFAULT 0,
  amount_of_adults    NUMBER DEFAULT 0,
  is_confirmed        NUMBER(1) DEFAULT 1,
  is_active           NUMBER(1) DEFAULT 1,
  CONSTRAINT pk_reservations PRIMARY KEY(id),
  CONSTRAINT fk_res_user       FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE types_of_tour (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name_of_type  VARCHAR2(45),
  is_active     NUMBER(1) DEFAULT 1,
  CONSTRAINT pk_types_of_tour PRIMARY KEY(id)
);

CREATE TABLE price (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  normal_price   NUMBER(7,2),
  reduced_price  NUMBER(7,2),
  is_active      NUMBER(1) DEFAULT 1,
  CONSTRAINT pk_price PRIMARY KEY(id)
);

CREATE TABLE tours (
  id                          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  supervisor_id               NUMBER,
  max_number_of_participants  NUMBER,
  date_start                  DATE,
  date_end                    DATE,
  place_id                    NUMBER,
  type_of_tour_id             NUMBER,
  price_id                    NUMBER,
  country                     VARCHAR2(45),
  region                      VARCHAR2(45),
  city                        VARCHAR2(45),
  accommodation               VARCHAR2(45),
  is_active                   NUMBER(1) DEFAULT 1,
  CONSTRAINT pk_tours         PRIMARY KEY(id),
  CONSTRAINT fk_tours_superv  FOREIGN KEY(supervisor_id)   REFERENCES users(id),
  CONSTRAINT fk_tours_type    FOREIGN KEY(type_of_tour_id)  REFERENCES types_of_tour(id),
  CONSTRAINT fk_tours_price   FOREIGN KEY(price_id)         REFERENCES price(id)
);


CREATE TABLE tour_has_reservations (
  reservation_id   NUMBER,
  tour_id          NUMBER,
  is_active        NUMBER(1) DEFAULT 1,
  is_price_reduced NUMBER(1) DEFAULT 0,
  CONSTRAINT pk_thr PRIMARY KEY(reservation_id, tour_id),
  CONSTRAINT fk_thr_res FOREIGN KEY(reservation_id) REFERENCES reservations(id),
  CONSTRAINT fk_thr_tour FOREIGN KEY(tour_id)        REFERENCES tours(id)
);


--DROP TABLE tour_has_reservations CASCADE CONSTRAINTS;
--DROP TABLE tours                 CASCADE CONSTRAINTS;
--DROP TABLE reservations          CASCADE CONSTRAINTS;
--DROP TABLE types_of_tour         CASCADE CONSTRAINTS;
--DROP TABLE price                 CASCADE CONSTRAINTS;
--DROP TABLE users                 CASCADE CONSTRAINTS;